In [5]:
import sys
from pathlib import Path

sys.path.append(str(Path("../app")))

from data.ingestion.yahoo import *

In [6]:
spy = download_asset(
    "SPY",
    "2023-01-01",
    "2024-01-01"
)

spy.head()

[*********************100%***********************]  1 of 1 completed

Price            Close
Date
2023-01-03  364.133911
2023-01-04  366.945068
2023-01-05  362.757050
2023-01-06  371.075836
2023-01-09  370.865570

In [7]:
tnx = download_asset(
    "^TNX",
    "2023-01-01",
    "2024-01-01"
)

tnx.head()

[*********************100%***********************]  1 of 1 completed

Price       Close
Date
2023-01-03  3.793
2023-01-04  3.709
2023-01-05  3.720
2023-01-06  3.569
2023-01-09  3.517

In [8]:
assets = download_assets(
    ["SPY", "GLD", "^VIX"],
    "2023-01-01",
    "2024-01-01"
)

aligned = align_assets(assets)
aligned.head()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

                   SPY         GLD       ^VIX
Price            Close       Close      Close
Date
2023-01-03  364.133911  171.059998  22.900000
2023-01-04  366.945068  172.669998  22.010000
2023-01-05  362.757050  170.520004  22.459999
2023-01-06  371.075836  173.710007  21.129999
2023-01-09  370.865570  174.100006  21.969999

In [9]:
save_parquet(spy, "test.parquet")

loaded = load_parquet("test.parquet")

loaded.equals(spy)

True

In [10]:
get_asset(
    "SPY",
    "2023-01-01",
    "2024-01-01"
)

[*********************100%***********************]  1 of 1 completed

Downloading...

Price            Close
Date
2023-01-03  364.133911
2023-01-04  366.945068
2023-01-05  362.757050
2023-01-06  371.075836
2023-01-09  370.865570
...                ...
2023-12-22  459.779968
2023-12-26  461.721283
2023-12-27  462.556213
2023-12-28  462.730988
2023-12-29  461.391296

[250 rows x 1 columns]

In [11]:
get_asset(
    "SPY",
    "2023-01-01",
    "2024-01-01"
)

Loading from cache...

Price            Close
Date
2023-01-03  364.133911
2023-01-04  366.945068
2023-01-05  362.757050
2023-01-06  371.075836
2023-01-09  370.865570
...                ...
2023-12-22  459.779968
2023-12-26  461.721283
2023-12-27  462.556213
2023-12-28  462.730988
2023-12-29  461.391296

[250 rows x 1 columns]

In [12]:
try:
    download_asset(
        "INVALID123",
        "2023-01-01",
        "2024-01-01"
    )
except Exception as e:
    print(e)

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: INVALID123"}}}
$INVALID123: possibly delisted; no timezone found
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['INVALID123']: possibly delisted; no timezone found

No data found for INVALID123

In [13]:
update_asset('SPY', filepath= 'test.parquet')

[*********************100%***********************]  1 of 1 completed

Price            Close
Date
2023-01-03  364.133911
2023-01-04  366.945068
2023-01-05  362.757050
2023-01-06  371.075836
2023-01-09  370.865570
...                ...
2026-07-24  738.929993
2026-07-27  739.090027
2026-07-28  740.859985
2026-07-29  729.460022
2026-07-30  741.690002

[896 rows x 1 columns]